name: GestionClientesSkyGael

on:
push:
branches:
-main
pull_request:
branches_
-main

jobs:
test:
runs-on: ubuntu-latest
steps:
- name: Clonar el repositorio
uses: actions/checkout@v2

- name: Configurar Python
uses:actions/setup-python@v2
with:
python-version: 3.9

- name: Ejecutar pruebas
run: echo "pruebas automatizadas en proceso..."
